spring:
  application:
    name: flow
  data:
    redis:
      host: 127.0.0.1
      port: 6379
server:
  port: 9010

scheduler:
  enabled: true
---
spring:
  config:
    activate:
      on-profile: test
  data:
    redis:
      host: 127.0.0.1
      port: 63790
scheduler:
  enabled: false

